# **Importing Libraries**

In [ ]:
import sklearn.datasets
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# **Data Collection and Processing**

In [ ]:
breast_cancer_dataset=sklearn.datasets.load_breast_cancer()

In [ ]:
df=pd.DataFrame(breast_cancer_dataset.data,columns=breast_cancer_dataset.feature_names)
df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [ ]:
df['Result']=breast_cancer_dataset.target
df['Result'].tail()

564    0
565    0
566    0
567    0
568    1
Name: Result, dtype: int64

In [ ]:
df.shape

(569, 31)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [ ]:
df['Result'].value_counts()

Result
1    357
0    212
Name: count, dtype: int64

In [ ]:
X=df.drop(columns='Result',axis=1)
y=df['Result']

# **Splitting into Train and Test**

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [ ]:
print(X_train.shape,X_test.shape)

(455, 30) (114, 30)


# **Standardize the Data**

In [ ]:
from sklearn.preprocessing import StandardScaler


In [ ]:
scaler=StandardScaler()
X_train_std=scaler.fit_transform(X_train)
X_test_std=scaler.transform(X_test)

In [ ]:
y_train

560    1
428    1
198    0
203    0
41     0
      ..
299    1
534    1
493    1
527    1
168    0
Name: Result, Length: 455, dtype: int64

In [ ]:
y_test

528    1
291    1
467    1
108    0
340    1
      ..
471    1
449    0
24     0
38     0
230    0
Name: Result, Length: 114, dtype: int64

# **Importing Tensorflow and keras**

In [ ]:
import tensorflow as tf
tf.random.set_seed(4)
from tensorflow import keras

# **Setting up the layers of Neural Network**

In [ ]:
model=keras.Sequential([
    keras.layers.Flatten(input_shape=(30,)),
    keras.layers.Dense(20,activation='relu'),
    keras.layers.Dense(2,activation='sigmoid')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


# **Compiling Neural Network**

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# **Training the Neural Network**

In [ ]:
history=model.fit(X_train_std,y_train,validation_split=0.1,epochs=10)

Epoch 1/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 3s 106ms/step - accuracy: 0.8999 - loss: 0.3604 - val_accuracy: 0.9783 - val_loss: 0.2693
Epoch 2/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9205 - loss: 0.2813 - val_accuracy: 0.9783 - val_loss: 0.2094
Epoch 3/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9314 - loss: 0.2295 - val_accuracy: 0.9783 - val_loss: 0.1716
Epoch 4/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9455 - loss: 0.1939 - val_accuracy: 0.9783 - val_loss: 0.1476
Epoch 5/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9527 - loss: 0.1684 - val_accuracy: 0.9783 - val_loss: 0.1317
Epoch 6/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9531 - loss: 0.1493 - val_accuracy: 0.9783 - val_loss: 0.1202
Epoch 7/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9568 - loss: 0.1342 - val_accuracy: 0.9783 - val_loss: 0.1112
Epoch 8/10
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9666 - loss: 0.1219 - val_accuracy: 0.9783 - val_los

# **Accuracy of the model on test data**

In [ ]:
loss,accuracy=model.evaluate(X_test_std,y_test)
print(accuracy)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.9728 - loss: 0.0980
0.9736841917037964


In [ ]:
print(X_test_std[0])

[-0.04462793 -1.41612656 -0.05903514 -0.16234067  2.0202457  -0.11323672
  0.18500609  0.47102419  0.63336386  0.26335737  0.53209124  2.62763999
  0.62351167  0.11405261  1.01246781  0.41126289  0.63848593  2.88971815
 -0.41675911  0.74270853 -0.32983699 -1.67435595 -0.36854552 -0.38767294
  0.32655007 -0.74858917 -0.54689089 -0.18278004 -1.23064515 -0.6268286 ]


In [ ]:
y_pred=model.predict(X_test_std)
y_pred

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[0.27896833, 0.6990744 ],
       [0.39464524, 0.58769286],
       [0.20567104, 0.9938666 ],
       [0.99996066, 0.0038773 ],
       [0.5442891 , 0.5560026 ],
       [0.99635524, 0.04116189],
       [0.4188006 , 0.8468616 ],
       [0.44787693, 0.9949024 ],
       [0.4775151 , 0.966184  ],
       [0.3359133 , 0.9773157 ],
       [0.5686928 , 0.6198542 ],
       [0.24950744, 0.89495075],
       [0.16393305, 0.9053851 ],
       [0.28503656, 0.839015  ],
       [0.3778836 , 0.970974  ],
       [0.98431826, 0.17596586],
       [0.24935499, 0.98835444],
       [0.14997983, 0.9839384 ],
       [0.32322896, 0.9830425 ],
       [0.961465  , 0.04405694],
       [0.56816834, 0.8885991 ],
       [0.3479539 , 0.993878  ],
       [0.34605914, 0.9843482 ],
       [0.27369922, 0.9936516 ],
       [0.33942628, 0.89045405],
       [0.9582461 , 0.1503807 ],
       [0.37500316, 0.9562788 ],
       [0.5208136 , 0.92197865],
       [0.94862646, 0.2539861 ],
       [0.97789806, 0.14968413],
       [0.

In [ ]:
y_pred[0]

array([0.27896833, 0.6990744 ], dtype=float32)

# **Convertion Prediction Probablity to the class labels**

In [ ]:
y_pred_labels=[int(np.argmax(i)) for i in y_pred]
print(y_pred_labels)

[1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0]


# **Building the prediction system**

In [ ]:
input_data = (20.57,17.77,132.9,1326,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,0.5435,0.7339,3.398,74.08,0.005225,0.01308,0.0186,0.0134,0.01389,0.003532,24.99,23.41,158.8,1956,0.1238,0.1866,0.2416,0.186,0.275,0.08902)

# change the input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the numpy array as we are predicting for one data point
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

# standardizing the input data
input_data_std = scaler.transform(input_data_reshaped)

prediction = model.predict(input_data_std)
print(prediction)

prediction_label = [np.argmax(prediction)]
print(prediction_label)

if(prediction_label[0] == 0):
  print('The tumor is Malignant')

else:
  print('The tumor is Benign')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
[[0.94862646 0.25398606]]
[np.int64(0)]
The tumor is Malignant


/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
